# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nicolas/rendu/rtype_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nicolas/rendu/rtype_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/nicolas/rendu/rtype_cpp/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicolas/rendu/rtype_cpp/CMakeFiles /home/nicolas/rendu/rtype_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicolas/rendu/rtype_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named R-Type

# Build rule for target.
R-Type: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 R-Type
.PHONY : R-Type

# fast build rule for target.
R-Type/fast:
	$(MAKE) -f CMakeFiles/R-Type.dir/build.make CMakeFiles/R-Type.dir/build
.PHONY : R-Type/fast

client/common/RenderWindow.o: client/common/RenderWindow.cpp.o
.PHONY : client/common/RenderWindow.o

# target to build an object file
client/common/RenderWindow.cpp.o:
	$(MAKE) -f CMakeFiles/R-Type.dir/build.make CMakeFiles/R-Type.dir/client/common/RenderWindow.cpp.o
.PHONY : client/common/RenderWindow.cpp.o

client/common/RenderWindow.i: client/common/RenderWindow.cpp.i
.PHONY : client/common/RenderWindow.i

# target to preprocess a source file
client/common/RenderWindow.cpp.i:
	$(MAKE) -f CMakeFiles/R-Type.dir/build.make CMakeFiles/R-Type.dir/client/common/RenderWindow.cpp.i
.PHONY : client/common/RenderWindow.cpp.i

client/common/RenderWindow.s: client/common/RenderWindow.cpp.s
.PHONY : client/common/RenderWindow.s

# target to generate assembly for a file
client/common/RenderWindow.cpp.s:
	$(MAKE) -f CMakeFiles/R-Type.dir/build.make CMakeFiles/R-Type.dir/client/common/RenderWindow.cpp.s
.PHONY : client/common/RenderWindow.cpp.s

client/common/Vector2.o: client/common/Vector2.cpp.o
.PHONY : client/common/Vector2.o

# target to build an object file
client/common/Vector2.cpp.o:
	$(MAKE) -f CMakeFiles/R-Type.dir/build.make CMakeFiles/R-Type.dir/client/common/Vector2.cpp.o
.PHONY : client/common/Vector2.cpp.o

client/common/Vector2.i: client/common/Vector2.cpp.i
.PHONY : client/common/Vector2.i

# target to preprocess a source file
client/common/Vector2.cpp.i:
	$(MAKE) -f CMakeFiles/R-Type.dir/build.make CMakeFiles/R-Type.dir/client/common/Vector2.cpp.i
.PHONY : client/common/Vector2.cpp.i

client/common/Vector2.s: client/common/Vector2.cpp.s
.PHONY : client/common/Vector2.s

# target to generate assembly for a file
client/common/Vector2.cpp.s:
	$(MAKE) -f CMakeFiles/R-Type.dir/build.make CMakeFiles/R-Type.dir/client/common/Vector2.cpp.s
.PHONY : client/common/Vector2.cpp.s

client/common/main.o: client/common/main.cpp.o
.PHONY : client/common/main.o

# target to build an object file
client/common/main.cpp.o:
	$(MAKE) -f CMakeFiles/R-Type.dir/build.make CMakeFiles/R-Type.dir/client/common/main.cpp.o
.PHONY : client/common/main.cpp.o

client/common/main.i: client/common/main.cpp.i
.PHONY : client/common/main.i

# target to preprocess a source file
client/common/main.cpp.i:
	$(MAKE) -f CMakeFiles/R-Type.dir/build.make CMakeFiles/R-Type.dir/client/common/main.cpp.i
.PHONY : client/common/main.cpp.i

client/common/main.s: client/common/main.cpp.s
.PHONY : client/common/main.s

# target to generate assembly for a file
client/common/main.cpp.s:
	$(MAKE) -f CMakeFiles/R-Type.dir/build.make CMakeFiles/R-Type.dir/client/common/main.cpp.s
.PHONY : client/common/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... R-Type"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... client/common/RenderWindow.o"
	@echo "... client/common/RenderWindow.i"
	@echo "... client/common/RenderWindow.s"
	@echo "... client/common/Vector2.o"
	@echo "... client/common/Vector2.i"
	@echo "... client/common/Vector2.s"
	@echo "... client/common/main.o"
	@echo "... client/common/main.i"
	@echo "... client/common/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

